language: ruby
sudo: false

rvm:
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - ruby-head
  - truffleruby
  - jruby
before_install:
  - gem update --system
  - gem install bundler:2.0.1
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: truffleruby
    - rvm: jruby
  fast_finish: true
