language: ruby
sudo: false

rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.5
  - ruby-head
  - jruby
before_install:
  - gem update --system
  - gem install bundler:2.0.1
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
  fast_finish: true
