language: ruby
sudo: false

rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - 2.6.2
  - ruby-head
  - jruby
before_install:
  - gem update --system
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
  fast_finish: true
