language: ruby
dist: xenial
os: linux

rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.2
  - 3.0.0
  - ruby-head
  - truffleruby
  - jruby
before_install:
  - gem update --system
  - gem install bundler:2.0.1
jobs:
  allow_failures:
    - rvm: ruby-head
    - rvm: truffleruby
    - rvm: jruby
  fast_finish: true
