language: ruby
sudo: false

rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - ruby-head
  - truffleruby
  - jruby
before_install:
  - gem update --system
  - gem install bundler:2.0.1
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: truffleruby
    - rvm: jruby
  fast_finish: true
